# Generated by Django 5.2.8 on 2026-04-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_loyalty_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='loyalty_balance',
            field=models.FloatField(default=0),
        ),
    ]
