# Generated by Django 5.2.8 on 2026-04-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_loyalty_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='shoe_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
