# Generated by Django 5.2.8 on 2026-04-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_shoe_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='shoe_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
