# Generated by Django 6.0.5 on 2026-05-20 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_saved_address_account_saved_city_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='saved_address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saved_city_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saved_city_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saved_district_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saved_district_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saved_postal_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saved_province_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saved_province_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saved_shipping_cost',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saved_shipping_service',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saved_subdistrict_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saved_subdistrict_name',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Alamat Baru', max_length=50)),
                ('province_id', models.CharField(max_length=20)),
                ('province_name', models.CharField(max_length=100)),
                ('city_id', models.CharField(max_length=20)),
                ('city_name', models.CharField(max_length=100)),
                ('district_id', models.CharField(max_length=20)),
                ('district_name', models.CharField(max_length=100)),
                ('subdistrict_id', models.CharField(max_length=20)),
                ('subdistrict_name', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('shipping_service', models.CharField(blank=True, max_length=100)),
                ('shipping_cost', models.FloatField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
