# Generated by Django 5.2.8 on 2025-11-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Contoh: 39, 40, 41', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
