# Generated by Django 5.2.8 on 2026-05-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, upload_to='photos/brands'),
        ),
    ]
