# Generated by Django 5.2.8 on 2026-04-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_district_order_district_id_order_subdistrict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='snap_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
