# Generated by Django 5.2.8 on 2026-04-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('image_proof', models.ImageField(upload_to='photos/returns/')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_account_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Menunggu Persetujuan'), ('Approved', 'Disetujui (Silakan Kirim Barang)'), ('Refunded', 'Dana Telah Dikembalikan'), ('Rejected', 'Permintaan Ditolak')], default='Pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('refund_proof', models.ImageField(blank=True, null=True, upload_to='photos/refund_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='order.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
