# Generated by Django 5.2.8 on 2026-04-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_returnrequest_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='province_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='snap_token',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subdistrict',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subdistrict_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='New', max_length=10),
        ),
    ]
