# Generated by Django 5.2.8 on 2026-04-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_city_id_remove_order_district_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='snap_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
