# Generated by Django 5.2.8 on 2026-04-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='snap_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
