# Generated by Django 5.2.8 on 2026-05-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
